import 'dart:html';
import 'package:rdart/bootstrap.dart';
import '../rview_bases.dart';
import '../../bootstrap/js/bootrap.js.dart' as bjs;
part 'collapse.dart';
part 'accordion.dart';
part 'alert.dart';
part 'breadcrumb.dart';
part 'card.dart';
part 'carousel.dart';
part 'dropdown.dart';
part 'list.dart';
part 'modal.dart';
part 'navbar.dart';
part 'offcanvas.dart';
part 'pagination.dart';
part 'popovers.dart';